// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hilblatimkqacigwnqbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbGJsYXRpbWtxYWNpZ3ducWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2ODgwMzAsImV4cCI6MjA4MjI2NDAzMH0.8OP4EugeH2lB25x1eJ9EXE1_2w340glrNlRBOc2rhJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);